/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.instituto.gui.panels;

import com.instituto.controladores.ControladorCurso;
import com.instituto.controladores.ControladorEspecialidad;
import com.instituto.controladores.ControladorNombreCurso;
import com.instituto.controladores.ControladorPeriodo;
import com.instituto.controladores.ControladorProfesor;
import com.instituto.entidades.Curso;
import com.instituto.entidades.NombreCurso;
import com.instituto.entidades.Profesor;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class panListarCursoDictar extends javax.swing.JPanel {
    private ControladorNombreCurso cc;
    private ControladorEspecialidad ce;
    private ControladorProfesor cp;
    private ControladorPeriodo cpe;
    private ControladorCurso ccu;
    private DefaultTableModel dtm;
    private List<Curso> cursos;
    /**
     * Creates new form panListarAlumnos
     */
    public panListarCursoDictar(ControladorNombreCurso cc, ControladorEspecialidad ce,
            ControladorProfesor cp, ControladorPeriodo cpe, ControladorCurso ccu) {
        this.cc= cc;
        this.ce= ce;
        this.cp= cp;
        this.cpe= cpe;
        this.ccu= ccu;
        initComponents();
        dtm= (DefaultTableModel)tabla.getModel();
        actualizarListaCursosDictar();
        
    }
    
    private void actualizarListaCursosDictar() {
        cursos= ccu.listarCursos();
        listarCursos("");
    }
    
    private void listarCursos(String nomb) {
        dtm.setRowCount(0);
        for (Curso c : cursos) {
            NombreCurso nc= cc.buscarNombreCurso(c.getIdNombreCurso().getIdNombreCursos());
            Profesor p= cp.buscarProfesor(c.getIdProfesor().getIdProfesor());
            String nombre= nc.getDescripcion();
            if(nombre.toLowerCase().startsWith(nomb.toLowerCase())) {
                Object rw[]= new Object[]{c.getIdCurso(), nc.getDescripcion(), 
                    c.getIdPeriodo().getIdPeriodo(), p.getNombres() + " " + 
                        p.getApellidoPaterno() + " " + p.getApellidoMaterno(), p.getActivo()};
                dtm.addRow(rw);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();

        jLabel1.setText("Nombre:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Periodo", "Profesor", "Activo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tabla);
        tabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        actualizarListaCursosDictar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
        listarCursos(txtNombre.getText());
    }//GEN-LAST:event_txtNombreKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}