/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.instituto.gui.panels;

import com.instituto.controladores.ControladorEspecialidad;
import com.instituto.controladores.ControladorNombreCurso;
import com.instituto.entidades.Especialidad;
import com.instituto.entidades.NombreCurso;
import com.instituto.util.MaximaLongitud;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author root
 */
public class panNuevoCurso extends javax.swing.JPanel {
    private ControladorNombreCurso cc;
    private ControladorEspecialidad ce;
    private List<Especialidad> especialidadaes;
    /**
     * Creates new form panNuevoCurso
     */
    public panNuevoCurso(ControladorNombreCurso cc, ControladorEspecialidad ce) {
        this.cc= cc;
        this.ce= ce;
        initComponents();
        especialidadaes = ce.listarEspecialidades();
        txtNombre.addKeyListener(new MaximaLongitud(100));
        llenarEspecialidades();
    }
    
    private void llenarEspecialidades() {
        cmbEspecialidad.removeAllItems();
        for (Especialidad e : especialidadaes) {
            cmbEspecialidad.addItem(e.getNombre());
        }
    }
    
    public void limpiar() {
        cmbEspecialidad.setSelectedIndex(0);
        txtNombre.setText("");
        Border b= cmbEspecialidad.getBorder();
        txtNombre.setBorder(b);
    }
    
    public void insertarCurso() {
        boolean res= true;
        NombreCurso nc= new NombreCurso();
        if(txtNombre.getText().length() > 0) {
            nc.setDescripcion(txtNombre.getText());
        }else res= false;
        if(cmbEspecialidad.getSelectedIndex() >= 0) {
            nc.setIdEspecialidad(especialidadaes.get(cmbEspecialidad.getSelectedIndex()));
        }else res= false;
        if(res) {
            Exception ex= cc.insertarNombreCurso(nc);
            if(ex == null) {
                JOptionPane.showMessageDialog(this, "Se registro con exito el curso", 
                    "Curso", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
            } else
                JOptionPane.showMessageDialog(this, ex.getMessage(), 
                    "Curso", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se registraron los campos obligatorios", 
                    "Curso", JOptionPane.INFORMATION_MESSAGE);
            Border b= BorderFactory.createEtchedBorder(Color.red, Color.red);
            txtNombre.setBorder(b);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbEspecialidad = new javax.swing.JComboBox();
        txtNombre = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();

        jLabel1.setText("Especialidad");

        jLabel2.setText("Nombre");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbEspecialidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAceptar)
                .addContainerGap(334, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        insertarCurso();
    }//GEN-LAST:event_btnAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox cmbEspecialidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
