/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.instituto.gui.panels;

import com.instituto.controladores.ControladorPeriodo;
import com.instituto.entidades.Periodo;
import com.instituto.util.MaximaLongitud;
import com.instituto.util.SoloNumeros;
import java.awt.Color;
import java.util.GregorianCalendar;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.Border;

/**
 *
 * @author root
 */
public class panNuevoPeriodo extends javax.swing.JPanel {

    private ControladorPeriodo cp;

    /**
     * Creates new form panNuevoCurso
     */
    public panNuevoPeriodo(ControladorPeriodo cp) {
        this.cp = cp;
        initComponents();
        txtCodigo.addKeyListener(new MaximaLongitud(6));
        txtCodigo.addKeyListener(new SoloNumeros());
    }

    public void limpiar() {
        txtFechaInicio.setText("");
        txtFechaFin.setText("");
        txtCodigo.setText("");
        Border b = new JTextField().getBorder();
        txtFechaInicio.setBorder(b);
        txtFechaFin.setBorder(b);
        txtCodigo.setBorder(b);
    }

    public void insertarPeriodo() {
        boolean res = true;
        Periodo p = new Periodo();
        if (txtFechaInicio.getText().length() > 0) {
            String d[] = txtFechaInicio.getText().split("/");
            p.setFechaInicio(new GregorianCalendar(Integer.parseInt(d[2]),
                    Integer.parseInt(d[1]) - 1, Integer.parseInt(d[0])).getTime());
        } else {
            res = false;
        }
        if (txtFechaFin.getText().length() > 0) {
            String d[] = txtFechaFin.getText().split("/");
            p.setFechaFin(new GregorianCalendar(Integer.parseInt(d[2]),
                    Integer.parseInt(d[1]) - 1, Integer.parseInt(d[0])).getTime());
        } else {
            res = false;
        }
        if (txtCodigo.getText().length() > 0) {
            p.setIdPeriodo(txtCodigo.getText());
        } else {
            res = false;
        }
        if (res) {
            if (p.getFechaInicio().getTime() < p.getFechaFin().getTime()) {
                Exception ex = cp.insertarPeriodo(p);
                if (ex == null) {
                    JOptionPane.showMessageDialog(this, "Se registro con exito el Periodo",
                            "Periodo", JOptionPane.INFORMATION_MESSAGE);
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(this, ex.getMessage(),
                            "Periodo", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "La fecha de inicio debe ser menor a la fecha de fin",
                            "Periodo", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se registraron los campos obligatorios",
                    "Periodo", JOptionPane.INFORMATION_MESSAGE);
            Border b = BorderFactory.createEtchedBorder(Color.red, Color.red);
            txtCodigo.setBorder(b);
            txtFechaFin.setBorder(b);
            txtFechaInicio.setBorder(b);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtFechaInicio = new javax.swing.JFormattedTextField();
        txtFechaFin = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Codigo");

        jLabel2.setText("Fecha Inicio");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha Fin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaFin)
                            .addComponent(txtCodigo)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAceptar)
                .addContainerGap(302, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        insertarPeriodo();
    }//GEN-LAST:event_btnAceptarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtFechaFin;
    private javax.swing.JFormattedTextField txtFechaInicio;
    // End of variables declaration//GEN-END:variables
}
