/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.instituto.gui.forms;

import com.instituto.controladores.ControladorAdministrativo;
import com.instituto.controladores.ControladorAlumno;
import com.instituto.controladores.ControladorCurso;
import com.instituto.controladores.ControladorDetallePagos;
import com.instituto.controladores.ControladorDetallePlanAcademico;
import com.instituto.controladores.ControladorEspecialidad;
import com.instituto.controladores.ControladorNombreCurso;
import com.instituto.controladores.ControladorPagos;
import com.instituto.controladores.ControladorPeriodo;
import com.instituto.controladores.ControladorPlanAcademico;
import com.instituto.controladores.ControladorProfesor;
import com.instituto.gui.panels.panListarAdministrativo;
import com.instituto.gui.panels.panListarAlumnos;
import com.instituto.gui.panels.panListarCursoDictar;
import com.instituto.gui.panels.panListarCursos;
import com.instituto.gui.panels.panListarDeudas;
import com.instituto.gui.panels.panListarEspecialidades;
import com.instituto.gui.panels.panListarPagos;
import com.instituto.gui.panels.panListarPeriodos;
import com.instituto.gui.panels.panListarPlanesAcademicos;
import com.instituto.gui.panels.panListarProfesores;
import com.instituto.gui.panels.panNuevaEspecialidad;
import com.instituto.gui.panels.panNuevoAdministrativo;
import com.instituto.gui.panels.panNuevoAlumno;
import com.instituto.gui.panels.panNuevoCurso;
import com.instituto.gui.panels.panNuevoCursoDictar;
import com.instituto.gui.panels.panNuevoPago;
import com.instituto.gui.panels.panNuevoPeriodo;
import com.instituto.gui.panels.panNuevoPlanAcademico;
import com.instituto.gui.panels.panNuevoProfesor;
import com.instituto.storedprocedures.GenerarPagos;
import java.awt.BorderLayout;
import javax.sql.DataSource;
import javax.swing.JOptionPane;
import org.springframework.context.ApplicationContext;
import org.springframework.dao.DataAccessException;

/**
 *
 * @author root
 */
public class frmPrincipal extends javax.swing.JFrame {

    private ApplicationContext context;

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal(ApplicationContext context) {
        initComponents();
        this.context = context;
        setLocation((getToolkit().getScreenSize().width - getWidth()) / 2,
                (getToolkit().getScreenSize().height - getHeight()) / 2);
        panMain.setLayout(new BorderLayout());
        hideLoading();
    }

    public void showLoading() {
        lblLoadingI.setVisible(true);
        lblLoadingT.setVisible(true);
    }

    public void hideLoading() {
        lblLoadingI.setVisible(false);
        lblLoadingT.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMain = new javax.swing.JPanel();
        statusBar = new javax.swing.JToolBar();
        lblLoadingI = new javax.swing.JLabel();
        lblLoadingT = new javax.swing.JLabel();
        bar = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();
        mnuAlumnos = new javax.swing.JMenu();
        mnuNuevoAlumno = new javax.swing.JMenuItem();
        mnuListarAlumnos = new javax.swing.JMenuItem();
        mnuAdministrativos = new javax.swing.JMenu();
        mnuNuevoAdministrativo = new javax.swing.JMenuItem();
        mnuListarAdministrativo = new javax.swing.JMenuItem();
        mnuProfesores = new javax.swing.JMenu();
        mnuNuevoProfesor = new javax.swing.JMenuItem();
        mnuListarProfesor = new javax.swing.JMenuItem();
        mnuCursos = new javax.swing.JMenu();
        mnuNuevoCurso = new javax.swing.JMenuItem();
        mnuListarCursos = new javax.swing.JMenuItem();
        mnuCursosDictar = new javax.swing.JMenuItem();
        ListarCursosDictar = new javax.swing.JMenuItem();
        mnuInscripcionCurso = new javax.swing.JMenuItem();
        mnuEspecialidades = new javax.swing.JMenu();
        mnuNuevaEspecilidad = new javax.swing.JMenuItem();
        mnuListarEspecialidades = new javax.swing.JMenuItem();
        mnuPeriodos = new javax.swing.JMenu();
        mnuNuevoPeriodo = new javax.swing.JMenuItem();
        mnuListarPeriodos = new javax.swing.JMenuItem();
        mnuPagos = new javax.swing.JMenu();
        mnuRegistrarPagos = new javax.swing.JMenuItem();
        mnuConsultarPagos = new javax.swing.JMenuItem();
        mnuConsultarDeudas = new javax.swing.JMenuItem();
        mnuGenerarPagos = new javax.swing.JMenuItem();
        mnuPlanAcademico = new javax.swing.JMenu();
        mnuNuevoPlanA = new javax.swing.JMenuItem();
        mnuListarPlanA = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panMainLayout = new javax.swing.GroupLayout(panMain);
        panMain.setLayout(panMainLayout);
        panMainLayout.setHorizontalGroup(
            panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );
        panMainLayout.setVerticalGroup(
            panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        statusBar.setFloatable(false);
        statusBar.setRollover(true);

        lblLoadingI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loading.gif"))); // NOI18N
        statusBar.add(lblLoadingI);

        lblLoadingT.setText("Cargando...");
        statusBar.add(lblLoadingT);

        mnuArchivo.setText("Archivo");

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuSalir);

        bar.add(mnuArchivo);

        mnuAlumnos.setText("Alumnos");

        mnuNuevoAlumno.setText("Nuevo Alumno");
        mnuNuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevoAlumnoActionPerformed(evt);
            }
        });
        mnuAlumnos.add(mnuNuevoAlumno);

        mnuListarAlumnos.setText("Listar Alumnos");
        mnuListarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarAlumnosActionPerformed(evt);
            }
        });
        mnuAlumnos.add(mnuListarAlumnos);

        bar.add(mnuAlumnos);

        mnuAdministrativos.setText("Administrativos");

        mnuNuevoAdministrativo.setText("Nuevo Administrativo");
        mnuNuevoAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevoAdministrativoActionPerformed(evt);
            }
        });
        mnuAdministrativos.add(mnuNuevoAdministrativo);

        mnuListarAdministrativo.setText("ListarAdministrativo");
        mnuListarAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarAdministrativoActionPerformed(evt);
            }
        });
        mnuAdministrativos.add(mnuListarAdministrativo);

        bar.add(mnuAdministrativos);

        mnuProfesores.setText("Profesores");

        mnuNuevoProfesor.setText("Nuevo Profesor");
        mnuNuevoProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevoProfesorActionPerformed(evt);
            }
        });
        mnuProfesores.add(mnuNuevoProfesor);

        mnuListarProfesor.setText("Listar Profesores");
        mnuListarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarProfesorActionPerformed(evt);
            }
        });
        mnuProfesores.add(mnuListarProfesor);

        bar.add(mnuProfesores);

        mnuCursos.setText("Cursos");

        mnuNuevoCurso.setText("Nuevo Curso");
        mnuNuevoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevoCursoActionPerformed(evt);
            }
        });
        mnuCursos.add(mnuNuevoCurso);

        mnuListarCursos.setText("Listar Cursos");
        mnuListarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarCursosActionPerformed(evt);
            }
        });
        mnuCursos.add(mnuListarCursos);

        mnuCursosDictar.setText("Nuevo Curso A Dictar");
        mnuCursosDictar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCursosDictarActionPerformed(evt);
            }
        });
        mnuCursos.add(mnuCursosDictar);

        ListarCursosDictar.setText("Listar Curso A Dictar");
        ListarCursosDictar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarCursosDictarActionPerformed(evt);
            }
        });
        mnuCursos.add(ListarCursosDictar);

        mnuInscripcionCurso.setText("Inscripcion Cursos");
        mnuCursos.add(mnuInscripcionCurso);

        bar.add(mnuCursos);

        mnuEspecialidades.setText("Especialidades");

        mnuNuevaEspecilidad.setText("Nueva Especialidad");
        mnuNuevaEspecilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevaEspecilidadActionPerformed(evt);
            }
        });
        mnuEspecialidades.add(mnuNuevaEspecilidad);

        mnuListarEspecialidades.setText("Listar Especialidades");
        mnuListarEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarEspecialidadesActionPerformed(evt);
            }
        });
        mnuEspecialidades.add(mnuListarEspecialidades);

        bar.add(mnuEspecialidades);

        mnuPeriodos.setText("Periodos");

        mnuNuevoPeriodo.setText("Nuevo Periodo");
        mnuNuevoPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevoPeriodoActionPerformed(evt);
            }
        });
        mnuPeriodos.add(mnuNuevoPeriodo);

        mnuListarPeriodos.setText("Listar Periodos");
        mnuListarPeriodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarPeriodosActionPerformed(evt);
            }
        });
        mnuPeriodos.add(mnuListarPeriodos);

        bar.add(mnuPeriodos);

        mnuPagos.setText("Pagos");

        mnuRegistrarPagos.setText("Registrar Pagos");
        mnuRegistrarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistrarPagosActionPerformed(evt);
            }
        });
        mnuPagos.add(mnuRegistrarPagos);

        mnuConsultarPagos.setText("Consultar Pagos");
        mnuConsultarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultarPagosActionPerformed(evt);
            }
        });
        mnuPagos.add(mnuConsultarPagos);

        mnuConsultarDeudas.setText("Consultar Deudas");
        mnuConsultarDeudas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultarDeudasActionPerformed(evt);
            }
        });
        mnuPagos.add(mnuConsultarDeudas);

        mnuGenerarPagos.setText("Generar Pagos Mes");
        mnuGenerarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGenerarPagosActionPerformed(evt);
            }
        });
        mnuPagos.add(mnuGenerarPagos);

        bar.add(mnuPagos);

        mnuPlanAcademico.setText("Plan Academico");

        mnuNuevoPlanA.setText("Nuevo Plan Academico");
        mnuNuevoPlanA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevoPlanAActionPerformed(evt);
            }
        });
        mnuPlanAcademico.add(mnuNuevoPlanA);

        mnuListarPlanA.setText("Listar Planes Academicos");
        mnuListarPlanA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarPlanAActionPerformed(evt);
            }
        });
        mnuPlanAcademico.add(mnuListarPlanA);

        bar.add(mnuPlanAcademico);

        setJMenuBar(bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuNuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevoAlumnoActionPerformed
        // TODO add your handling code here:
        panMain.removeAll();
        panMain.add(new panNuevoAlumno(context.getBean(ControladorAlumno.class),
                null), BorderLayout.CENTER);
        panMain.updateUI();
        pack();
    }//GEN-LAST:event_mnuNuevoAlumnoActionPerformed

    private void mnuListarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarAlumnosActionPerformed
        // TODO add your handling code here:
        panMain.removeAll();
        panMain.add(new panListarAlumnos(context.getBean(ControladorAlumno.class)),
                BorderLayout.CENTER);
        panMain.updateUI();
        pack();
    }//GEN-LAST:event_mnuListarAlumnosActionPerformed

    private void mnuNuevoAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevoAdministrativoActionPerformed
        // TODO add your handling code here:
        panMain.removeAll();
        panMain.add(new panNuevoAdministrativo(context.getBean(ControladorAdministrativo.class),
                null), BorderLayout.CENTER);
        panMain.updateUI();
        pack();
    }//GEN-LAST:event_mnuNuevoAdministrativoActionPerformed

    private void mnuListarAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarAdministrativoActionPerformed
        // TODO add your handling code here:
        panMain.removeAll();
        panMain.add(new panListarAdministrativo(context.getBean(ControladorAdministrativo.class),
                this), BorderLayout.CENTER);
        panMain.updateUI();
        pack();
    }//GEN-LAST:event_mnuListarAdministrativoActionPerformed

    private void mnuNuevoProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevoProfesorActionPerformed
        // TODO add your handling code here:
        panMain.removeAll();
        panMain.add(new panNuevoProfesor(context.getBean(ControladorProfesor.class),
                null), BorderLayout.CENTER);
        panMain.updateUI();
        pack();
    }//GEN-LAST:event_mnuNuevoProfesorActionPerformed

    private void mnuListarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarProfesorActionPerformed
        // TODO add your handling code here:
        panMain.removeAll();
        panMain.add(new panListarProfesores(context.getBean(ControladorProfesor.class)),
                BorderLayout.CENTER);
        panMain.updateUI();
        pack();
    }//GEN-LAST:event_mnuListarProfesorActionPerformed

    private void mnuNuevaEspecilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevaEspecilidadActionPerformed
        // TODO add your handling code here:
        panMain.removeAll();
        panMain.add(new panNuevaEspecialidad(context.getBean(ControladorEspecialidad.class)),
                BorderLayout.CENTER);
        panMain.updateUI();
        pack();
    }//GEN-LAST:event_mnuNuevaEspecilidadActionPerformed

    private void mnuListarEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarEspecialidadesActionPerformed
        // TODO add your handling code here:
        panMain.removeAll();
        panMain.add(new panListarEspecialidades(context.getBean(ControladorEspecialidad.class)),
                BorderLayout.CENTER);
        panMain.updateUI();
        pack();
    }//GEN-LAST:event_mnuListarEspecialidadesActionPerformed

    private void mnuNuevoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevoCursoActionPerformed
        // TODO add your handling code here:
        panMain.removeAll();
        panMain.add(new panNuevoCurso(context.getBean(ControladorNombreCurso.class),
                context.getBean(ControladorEspecialidad.class)),
                BorderLayout.CENTER);
        panMain.updateUI();
        pack();
    }//GEN-LAST:event_mnuNuevoCursoActionPerformed

    private void mnuListarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarCursosActionPerformed
        // TODO add your handling code here:
        panMain.removeAll();
        panMain.add(new panListarCursos(context.getBean(ControladorNombreCurso.class),
                context.getBean(ControladorEspecialidad.class)),
                BorderLayout.CENTER);
        panMain.updateUI();
        pack();
    }//GEN-LAST:event_mnuListarCursosActionPerformed

    private void mnuNuevoPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevoPeriodoActionPerformed
        // TODO add your handling code here:
        panMain.removeAll();
        panMain.add(new panNuevoPeriodo(context.getBean(ControladorPeriodo.class)),
                BorderLayout.CENTER);
        panMain.updateUI();
        pack();
    }//GEN-LAST:event_mnuNuevoPeriodoActionPerformed

    private void mnuListarPeriodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarPeriodosActionPerformed
        // TODO add your handling code here:
        panMain.removeAll();
        panMain.add(new panListarPeriodos(context.getBean(ControladorPeriodo.class)),
                BorderLayout.CENTER);
        panMain.updateUI();
        pack();
    }//GEN-LAST:event_mnuListarPeriodosActionPerformed

    private void mnuCursosDictarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCursosDictarActionPerformed
        // TODO add your handling code here:
        panMain.removeAll();
        panMain.add(new panNuevoCursoDictar(context.getBean(ControladorNombreCurso.class),
                context.getBean(ControladorEspecialidad.class),
                context.getBean(ControladorProfesor.class),
                context.getBean(ControladorPeriodo.class),
                context.getBean(ControladorCurso.class)));
        panMain.updateUI();
        pack();
    }//GEN-LAST:event_mnuCursosDictarActionPerformed

    private void ListarCursosDictarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarCursosDictarActionPerformed
        // TODO add your handling code here:
        panMain.removeAll();
        panMain.add(new panListarCursoDictar(context.getBean(ControladorNombreCurso.class),
                context.getBean(ControladorEspecialidad.class),
                context.getBean(ControladorProfesor.class),
                context.getBean(ControladorPeriodo.class),
                context.getBean(ControladorCurso.class)));
        panMain.updateUI();
        pack();
    }//GEN-LAST:event_ListarCursosDictarActionPerformed

    private void mnuGenerarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGenerarPagosActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "¿Esta seguro de generar los pagos?", "Pagos", JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            double monto;
            String s= JOptionPane.showInputDialog(this, "Ingrese el monto a cobrar", 
                    "Pagos", JOptionPane.INFORMATION_MESSAGE);
            if(s != null) {
                try {
                    monto= Double.parseDouble(s);
                    GenerarPagos gp= new GenerarPagos((DataSource)context.getBean("dataSource"), monto);
                    gp.generar();
                    JOptionPane.showMessageDialog(this, "Se generaron los pagos con exito", "Pagos", 
                        JOptionPane.INFORMATION_MESSAGE);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Pagos", 
                        JOptionPane.ERROR_MESSAGE);
                    mnuGenerarPagosActionPerformed(evt);
                } catch (DataAccessException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Pagos", 
                        JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Se cancelo la operacion", "Pagos", 
                        JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Se cancelo la operacion", "Pagos", 
                        JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_mnuGenerarPagosActionPerformed

    private void mnuRegistrarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistrarPagosActionPerformed
        // TODO add your handling code here:
        panMain.removeAll();
        panMain.add(new panNuevoPago(context.getBean(ControladorPagos.class), 
                context.getBean(ControladorDetallePagos.class),
                context.getBean(ControladorAlumno.class)));
        panMain.updateUI();
        pack();
    }//GEN-LAST:event_mnuRegistrarPagosActionPerformed

    private void mnuConsultarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultarPagosActionPerformed
        // TODO add your handling code here:
        panMain.removeAll();
        panMain.add(new panListarPagos(context.getBean(ControladorDetallePagos.class),
                context.getBean(ControladorAlumno.class)));
        panMain.updateUI();
        pack();
    }//GEN-LAST:event_mnuConsultarPagosActionPerformed

    private void mnuConsultarDeudasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultarDeudasActionPerformed
        // TODO add your handling code here:
        panMain.removeAll();
        panMain.add(new panListarDeudas(context.getBean(ControladorPagos.class),
                context.getBean(ControladorAlumno.class)));
        panMain.updateUI();
        pack();
    }//GEN-LAST:event_mnuConsultarDeudasActionPerformed

    private void mnuNuevoPlanAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevoPlanAActionPerformed
        // TODO add your handling code here:
        panMain.removeAll();
        panMain.add(new panNuevoPlanAcademico(context.getBean(ControladorPlanAcademico.class), 
                context.getBean(ControladorDetallePlanAcademico.class), 
                context.getBean(ControladorEspecialidad.class), 
                context.getBean(ControladorNombreCurso.class)));
        panMain.updateUI();
        pack();
    }//GEN-LAST:event_mnuNuevoPlanAActionPerformed

    private void mnuListarPlanAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarPlanAActionPerformed
        // TODO add your handling code here:
        panMain.removeAll();
        panMain.add(new panListarPlanesAcademicos(context.getBean(ControladorPlanAcademico.class),
                context.getBean(ControladorEspecialidad.class), 
                context.getBean(ControladorDetallePlanAcademico.class)));
        panMain.updateUI();
        pack();
    }//GEN-LAST:event_mnuListarPlanAActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ListarCursosDictar;
    private javax.swing.JMenuBar bar;
    private javax.swing.JLabel lblLoadingI;
    private javax.swing.JLabel lblLoadingT;
    private javax.swing.JMenu mnuAdministrativos;
    private javax.swing.JMenu mnuAlumnos;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuConsultarDeudas;
    private javax.swing.JMenuItem mnuConsultarPagos;
    private javax.swing.JMenu mnuCursos;
    private javax.swing.JMenuItem mnuCursosDictar;
    private javax.swing.JMenu mnuEspecialidades;
    private javax.swing.JMenuItem mnuGenerarPagos;
    private javax.swing.JMenuItem mnuInscripcionCurso;
    private javax.swing.JMenuItem mnuListarAdministrativo;
    private javax.swing.JMenuItem mnuListarAlumnos;
    private javax.swing.JMenuItem mnuListarCursos;
    private javax.swing.JMenuItem mnuListarEspecialidades;
    private javax.swing.JMenuItem mnuListarPeriodos;
    private javax.swing.JMenuItem mnuListarPlanA;
    private javax.swing.JMenuItem mnuListarProfesor;
    private javax.swing.JMenuItem mnuNuevaEspecilidad;
    private javax.swing.JMenuItem mnuNuevoAdministrativo;
    private javax.swing.JMenuItem mnuNuevoAlumno;
    private javax.swing.JMenuItem mnuNuevoCurso;
    private javax.swing.JMenuItem mnuNuevoPeriodo;
    private javax.swing.JMenuItem mnuNuevoPlanA;
    private javax.swing.JMenuItem mnuNuevoProfesor;
    private javax.swing.JMenu mnuPagos;
    private javax.swing.JMenu mnuPeriodos;
    private javax.swing.JMenu mnuPlanAcademico;
    private javax.swing.JMenu mnuProfesores;
    private javax.swing.JMenuItem mnuRegistrarPagos;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JPanel panMain;
    private javax.swing.JToolBar statusBar;
    // End of variables declaration//GEN-END:variables
}
